### ISSUE TITLE
Script Starts but no prompt at bookie

### ISSUE THREAD

**Issue by EagLeTaLoN713** [kurdt94/k_bookie#1]
Is this script still working? I am unable to get the prompt to speak to the bookie

**Comment by kurdt94** [comment]
- Sorry for the late reply. Haven't been on github for a while. I see some things have changed, and the prompt are indeed no longer working. Currently am rewriting the prompts. Thanks for pointing this out. Regards.
- update : GetPlayerServerId() needed an argument, like so : GetPlayerServerId(GetPlayerIndex()).

**Comment by kurdt94** [comment]
-- no further action required
